# Generated by Django 2.2 on 2019-09-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('status', models.TextField(choices=[('monitors', 'monitors'), ('processors', 'processors'), ('other', 'other'), ('video card', 'video card'), ('components', 'components'), ('laptops', 'laptops'), ('motherboards', 'motherboards'), ('RAM', 'RAM'), ('cooling systems', 'cooling systems'), ('power supplies', 'power supplies'), ('cases', 'cases')], default='other', max_length=40, verbose_name='Status')),
                ('balance', models.IntegerField(verbose_name='Balance')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
